'use strict'

const isObject = require('./isObject')
const cloneObj = require('./util/cloneObj')

/**
 * this method creates an object with the same values as object and
 * keys generated by running each own enumerable
 * string keyed property of object thru iteratee.
 * @param {Object} obj The object to iterate over.
 * @param {Function} mapper The function invoked per iteration.
 * @returns {Object} Returns the new mapped object.
 */
const mapKeys = (obj, mapper) => {
  if (!isObject(obj)) {
    return obj
  }
  
  const clone = cloneObj(obj)

  return Object.entries(clone).reduce((acc, [key, value]) => ({
    ...acc,
    [mapper(value, key, clone)]: value
  }), {})
}

module.exports = mapKeys
